controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
    prefix: '/{_locale}'

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"