controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
    prefix: '/{_locale}'

live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: '/{_locale}/_components'

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"