controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'
    prefix: '/{_locale}'

# app/config/routing.yml
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"